@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [HausController]
  [HausResolver]

  [HausService]

  [Repository<Haus>]
}

cloud {
    [TypeORM]
}

cloud {
    [nest-keycloak-connect]
}

database "DB haus" {
    [Tabelle haus]
    [Tabelle adresse]
    [Tabelle person]
}

node {
    [Keycloak]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [HausController]
[RequestLoggerMiddleware] ~~> [HausResolver]

[HausController] ..> [HausService]
[HausResolver] ..> [HausService]
[HausService] ..> [Repository<Haus>]

[Repository<Haus>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle haus]
[TypeORM] ~~> [Tabelle adresse]
[TypeORM] ~~> [Tabelle person]

[HausController] ..> [nest-keycloak-connect]
[nest-keycloak-connect] ~~> [Keycloak]

@enduml
