name: Haus CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      cache-key: ${{ steps.setup-deps.outputs.cache-key }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-fund --no-audit

      - name: Cache dependencies
        id: setup-deps
        run: echo "::set-output name=cache-key::${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"

      - name: Run build
        run: npm run build --if-present

  eslint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Run eslint
        run: npm run eslint

  audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Run audit
        run: npm audit --omit=dev

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Run tests
        run: npm t
