name: Haus CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-fund --no-audit

      - name: Run build
        run: npm run build --if-present

  eslint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install ESLint
        run: npm install eslint@8.57.0

      - name: Run eslint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run audit
        run: npm audit --omit=dev

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Tests successfully passed"
