name: Haus CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-fund --no-audit

      - name: Run build
        run: npm run build --if-present

      - name: Run eslint
        run: npm run eslint

      - name: Run audit
        run: npm audit --omit=dev

      - name: Run tests
        run: npm t


